App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['new', 'edit']
    lalitude:
      - Range:
          min: -90
          max: 90
          groups: [ 'new', 'edit']
      - NotBlank:
          groups: [ 'new', 'edit' ]
    longitude:
      - Range:
          min: -180
          max: 180
          groups: [ 'new', 'edit']
      - NotBlank:
          groups: [ 'new', 'edit' ]

