weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

weather_country_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:countryCityAction

app_logout:
  path: /logout
  methods: GET

